services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:00000@db:3306/book_api
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 00000
      MYSQL_DATABASE: book_api
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6380:6379"

volumes:
  mysql_data:
